server:
  port: 9001

spring:
  application:
    name: alibaba-pay
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=
      UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  zipkin:
    base-url: http://192.168.120.18:9411
  sleuth:
    sampler:
      #      采样率probability介于 0-1之间，一般为0.5
      probability: 1
  cloud:
    nacos:
      discovery:
        enabled: true #如果不想使用 Nacos 作为您的服务注册与发现，可以将 spring.cloud.nacos.discovery.enabled 设置为 false。
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
#       spring-cloud-starter-alibaba-nacos-discovery 在实现的时候提供了一个EndPoint,EndPoint的访问地址为
#  http://localhost:9001/actuator/nacos-discovery   subscribe: 显示了当前有哪些服务订阅者

