server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order
  cloud:
    zookeeper:
      connect-string: 192.168.232.128:2181

#设置feign客户端超时时间
ribbon:
#建立连接，读取资源完成需要的时间
  ReadTimeout: 5000
#  建立连接需要的时间
  ConnectTimeout: 5000
swagger:
  enable: true

logging:
  level:
    # 设置 PaymentFeignService 的日志级别（注：不是Controller） copy reference （复制全路径）
    com.atguigu.springcloud.service.PaymentFeignService: debug


# feign 中启用hystrix
feign:
  hystrix:
    enabled: true